const CONSTANTS = {
  WELCOME_PAGE_URL: "https://abinjohn123.github.io/sidesy-landing/",
  POPUP_LINKS: [
    {
      label: "See Sidesy in action",
      description: "A quick, 20-second walkthrough",
      icon: "popup/icons/walkthrough.svg",
      hoverColor: "#4285f4",
      url: "https://abinjohn123.github.io/sidesy-landing/",
    },
    {
      label: "Having trouble? Reach out",
      description: "I'd love to help!",
      icon: "popup/icons/feedback.svg",
      hoverColor: "#e8453c",
      url: "mailto:builtbyabin@gmail.com?subject=Sidesy%20Feedback",
    },
    {
      label: "Enjoy using? Leave a review",
      description: "Help spread Sidesy to more people",
      icon: "popup/icons/review.svg",
      hoverColor: "#f4b400",
      url: "https://chromewebstore.google.com/detail/sidesy-your-comments-side/mlceikceecooilkgiikkopipedhjjech",
    },
    {
      label: "Love Sidesy? Buy me a coffee",
      description: "If you're feeling extra generous :)",
      icon: "popup/icons/donate.svg",
      hoverColor: "#34a853",
      url: "https://buymeacoffee.com/abin.john",
    },
    {
      label: "Conduktor",
      description: "Spotlight-style launcher for Chrome",
      icon: "popup/icons/conduktor.svg",
      hoverColor: "#f85842",
      url: "https://chromewebstore.google.com/detail/conduktor-search-rename-g/ppemfnloahkomglmckngiioogeibdbdh",
      sectionLabel: "Also from the developer",
    },
  ],
  ANNOUNCEMENT: {
    items: [
      "Toggle via Shortcut\nYou can now toggle the comments position using {{TOGGLE_SHORTCUT}}.",
      "Seamless View Switching\nWhen you toggle comments position, Sidesy restores scroll so you can keep reading without interruption.",
    ],
  },
  DEVELOPER_MESSAGE: {
    enabled: true,
    id: "conduktor-2026-05",
    title: "Hi, it's Abin from Sidesy",
    bodyParagraphs: [
      "I just launched a new extension called Conduktor, a Spotlight-style launcher for Chrome.",
      "Search tabs, manage tab groups, and run browser actions without leaving the keyboard. Built for keyboard-first users, productivity geeks, and tab hoarders.",
      "Free for 30 days, no credit card needed. 🙂",
    ],
    ctaLabel: "Check it out",
    remindLabel: "Remind later",
    dismissLabel: "Discard",
    url: "https://chromewebstore.google.com/detail/conduktor-search-rename-g/ppemfnloahkomglmckngiioogeibdbdh",
    existingUserDelayDays: 3,
    newUserDelayDays: 14,
    remindLaterDays: 14,
    maxReminders: 1,
    showDelayMs: 6500,
  },
};
